// blog-angular/src/app/pages/post-detail.ts
import { Component, inject, input, OnInit, signal } from "@angular/core";
import { DatePipe } from "@angular/common";
import { Router, RouterLink } from "@angular/router";
import { Auth } from "../auth";
import { BlogApi } from "../blog-api";
import { Markdown } from "../markdown";
import { errorMessage, Post } from "../models";

@Component({
  selector: "app-post-detail",
  imports: [RouterLink, DatePipe, Markdown],
  template: `
    @if (error()) {
      <p class="text-red-500 text-sm">{{ error() }}</p>
    } @else if (post(); as post) {
      <article>
        <time class="text-xs uppercase tracking-wide text-zinc-500">
          {{ post.created_at | date: "longDate" }}
        </time>
        <h1 class="mt-1 text-3xl font-semibold tracking-tight">{{ post.title }}</h1>
        @if (auth.authed()) {
          <div class="mt-3 flex gap-3 text-sm">
            <a
              [routerLink]="['/edit', post.slug]"
              class="text-violet-600 dark:text-violet-400 hover:underline"
            >
              Edit
            </a>
            <button (click)="remove(post)" class="text-red-500 hover:underline">Delete</button>
          </div>
        }
        <app-markdown class="mt-6 block" [source]="post.body" />
      </article>
    } @else {
      <p class="text-zinc-500 text-sm">Loading…</p>
    }
  `,
})
export class PostDetail implements OnInit {
  readonly slug = input.required<string>();
  protected readonly auth = inject(Auth);
  private readonly api = inject(BlogApi);
  private readonly router = inject(Router);
  protected readonly post = signal<Post | null>(null);
  protected readonly error = signal<string | null>(null);

  ngOnInit(): void {
    this.api
      .get(this.slug())
      .then((post) => this.post.set(post))
      .catch((e: unknown) => this.error.set(errorMessage(e)));
  }

  async remove(post: Post): Promise<void> {
    if (!confirm("Delete this post?")) return;
    try {
      await this.api.delete(post.id);
      await this.router.navigateByUrl("/");
    } catch (e) {
      this.error.set(errorMessage(e));
    }
  }
}

// blog-react/src/pages/PostDetail.tsx
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router";
import { deletePost, getPost, type Post } from "../api";
import { Markdown } from "../markdown";

export function PostDetail({ authed }: { authed: boolean }) {
  const { slug } = useParams<{ slug: string }>();
  const [post, setPost] = useState<Post | null>(null);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    if (!slug) return;
    getPost(slug)
      .then(setPost)
      .catch((e: Error) => setError(e.message));
  }, [slug]);

  async function handleDelete() {
    if (!post || !confirm("Delete this post?")) return;
    try {
      await deletePost(post.id);
      navigate("/");
    } catch (e) {
      setError((e as Error).message);
    }
  }

  if (error) return <p className="text-red-500 text-sm">{error}</p>;
  if (!post) return <p className="text-zinc-500 text-sm">Loading…</p>;

  return (
    <article>
      <time className="text-xs uppercase tracking-wide text-zinc-500">
        {new Date(post.created_at).toLocaleDateString(undefined, {
          year: "numeric",
          month: "long",
          day: "numeric",
        })}
      </time>
      <h1 className="mt-1 text-3xl font-semibold tracking-tight">{post.title}</h1>
      {authed && (
        <div className="mt-3 flex gap-3 text-sm">
          <Link
            to={`/edit/${post.slug}`}
            className="text-violet-600 dark:text-violet-400 hover:underline"
          >
            Edit
          </Link>
          <button onClick={handleDelete} className="text-red-500 hover:underline">
            Delete
          </button>
        </div>
      )}
      <div className="mt-6">
        <Markdown source={post.body} />
      </div>
    </article>
  );
}
